/* ==========================================================================
   KT-SUPERSYSTEM ERP - SEED DATA
   Realistic Enterprise Master Data: Products, Warehouses, Suppliers,
   Customers, Purchase Orders, Sales Orders, Approvals & Movements
   ========================================================================== */

const INITIAL_ERP_DATA = {
  warehouses: [
    { id: 'WH-MAIN', name: 'Central Mega-Hub (North Dallas)', code: 'MAIN', manager: 'Marcus Vance', capacity: '85%' },
    { id: 'WH-BAYB', name: 'Tech & Precision Hub (Bay B - Austin)', code: 'BAY-B', manager: 'Elena Rostova', capacity: '62%' },
    { id: 'WH-COLD', name: 'Climate Controlled Depot (Houston)', code: 'COLD', manager: 'Derrick Hall', capacity: '44%' }
  ],

  products: [
    {
      id: 'PRD-101',
      sku: 'CPU-ARM-OCTA',
      name: 'UltraCore ARM Octa-Core Processor Module',
      category: 'Computing Modules',
      description: 'Industrial-grade 3.2GHz edge AI compute unit with integrated NPU.',
      unitCost: 185.00,
      sellingPrice: 340.00,
      unit: 'pcs',
      minStock: 50,
      reorderQty: 100,
      preferredSupplierId: 'SUP-01',
      binLocation: 'A-02-14',
      lotNumber: 'LOT-2026-99A',
      expiryDate: '2028-12-31',
      stockByWarehouse: { 'WH-MAIN': 85, 'WH-BAYB': 40, 'WH-COLD': 15 },
      totalStock: 140,
      reservedStock: 25,
      onOrderStock: 50
    },
    {
      id: 'PRD-102',
      sku: 'SNS-LIDAR-360',
      name: 'Solid-State 360° LiDAR Sensor Suite',
      category: 'Precision Sensors',
      description: 'High-density point cloud optical rangefinder for autonomous robots.',
      unitCost: 420.00,
      sellingPrice: 780.00,
      unit: 'pcs',
      minStock: 20,
      reorderQty: 40,
      preferredSupplierId: 'SUP-02',
      binLocation: 'B-05-02',
      lotNumber: 'LOT-2026-44B',
      expiryDate: '2029-06-15',
      stockByWarehouse: { 'WH-MAIN': 12, 'WH-BAYB': 6, 'WH-COLD': 0 },
      totalStock: 18,
      reservedStock: 10,
      onOrderStock: 30
    },
    {
      id: 'PRD-103',
      sku: 'PWR-BMS-48V',
      name: 'Modular Smart 48V Battery Management System',
      category: 'Power Management',
      description: 'CAN-bus compatible multi-cell balancer with thermal runaway protection.',
      unitCost: 74.50,
      sellingPrice: 155.00,
      unit: 'pcs',
      minStock: 60,
      reorderQty: 120,
      preferredSupplierId: 'SUP-03',
      binLocation: 'C-01-09',
      lotNumber: 'LOT-2026-12C',
      expiryDate: '2027-08-20',
      stockByWarehouse: { 'WH-MAIN': 190, 'WH-BAYB': 50, 'WH-COLD': 20 },
      totalStock: 260,
      reservedStock: 40,
      onOrderStock: 0
    },
    {
      id: 'PRD-104',
      sku: 'OPT-100G-QSFP',
      name: '100G QSFP28 Single-Mode Optical Transceiver',
      category: 'Networking',
      description: '1310nm 10km transmission duplex LC fiber transceiver module.',
      unitCost: 110.00,
      sellingPrice: 245.00,
      unit: 'pcs',
      minStock: 40,
      reorderQty: 80,
      preferredSupplierId: 'SUP-04',
      binLocation: 'A-08-22',
      lotNumber: 'LOT-2026-08D',
      expiryDate: '2030-01-01',
      stockByWarehouse: { 'WH-MAIN': 18, 'WH-BAYB': 10, 'WH-COLD': 0 },
      totalStock: 28, // Low Stock trigger (< 40)
      reservedStock: 15,
      onOrderStock: 0
    },
    {
      id: 'PRD-105',
      sku: 'IOT-GW-5G',
      name: 'Ruggedized IP67 Industrial 5G Gateway',
      category: 'Industrial IoT',
      description: 'Wide-temp DIN-rail edge gateway with Dual SIM and GPS fallback.',
      unitCost: 290.00,
      sellingPrice: 560.00,
      unit: 'pcs',
      minStock: 25,
      reorderQty: 50,
      preferredSupplierId: 'SUP-01',
      binLocation: 'B-11-04',
      lotNumber: 'LOT-2026-67E',
      expiryDate: '2029-10-30',
      stockByWarehouse: { 'WH-MAIN': 45, 'WH-BAYB': 25, 'WH-COLD': 5 },
      totalStock: 75,
      reservedStock: 12,
      onOrderStock: 0
    },
    {
      id: 'PRD-106',
      sku: 'MEM-DDR5-ECC',
      name: '64GB Industrial ECC DDR5 SO-DIMM',
      category: 'Computing Modules',
      description: '5600MT/s military spec memory module with onboard thermal sensor.',
      unitCost: 95.00,
      sellingPrice: 195.00,
      unit: 'pcs',
      minStock: 80,
      reorderQty: 150,
      preferredSupplierId: 'SUP-05',
      binLocation: 'A-03-01',
      lotNumber: 'LOT-2026-88F',
      expiryDate: '2031-12-31',
      stockByWarehouse: { 'WH-MAIN': 140, 'WH-BAYB': 60, 'WH-COLD': 30 },
      totalStock: 230,
      reservedStock: 30,
      onOrderStock: 0
    },
    {
      id: 'PRD-107',
      sku: 'SNS-IMU-6DOF',
      name: 'Precision MEMS 6-DoF Inertial Unit',
      category: 'Precision Sensors',
      description: 'Sub-degree gyroscope and accelerometer for avionics stabilization.',
      unitCost: 35.00,
      sellingPrice: 85.00,
      unit: 'pcs',
      minStock: 100,
      reorderQty: 250,
      preferredSupplierId: 'SUP-02',
      binLocation: 'C-04-18',
      lotNumber: 'LOT-2026-19G',
      expiryDate: '2028-05-14',
      stockByWarehouse: { 'WH-MAIN': 310, 'WH-BAYB': 120, 'WH-COLD': 0 },
      totalStock: 430,
      reservedStock: 50,
      onOrderStock: 0
    },
    {
      id: 'PRD-108',
      sku: 'ENC-ALUM-DIN',
      name: 'Extruded Aluminum Enclosure (DIN Mount)',
      category: 'Mechanical Parts',
      description: 'Anodized black chassis with heat-sink fins and IP65 silicone gaskets.',
      unitCost: 22.00,
      sellingPrice: 48.00,
      unit: 'pcs',
      minStock: 75,
      reorderQty: 200,
      preferredSupplierId: 'SUP-03',
      binLocation: 'D-01-05',
      lotNumber: 'LOT-2026-31H',
      expiryDate: '2035-01-01',
      stockByWarehouse: { 'WH-MAIN': 16, 'WH-BAYB': 8, 'WH-COLD': 0 },
      totalStock: 24, // Critical Low stock (< 75)
      reservedStock: 0,
      onOrderStock: 0
    },
    {
      id: 'PRD-109',
      sku: 'CAB-M12-8PIN',
      name: 'Shielded M12 8-Pin Industrial Ethernet Cable (5m)',
      category: 'Networking',
      description: 'Oil-resistant PUR jacket rated for drag chain continuous flex.',
      unitCost: 14.20,
      sellingPrice: 32.50,
      unit: 'pcs',
      minStock: 50,
      reorderQty: 100,
      preferredSupplierId: 'SUP-04',
      binLocation: 'D-03-12',
      lotNumber: 'LOT-2026-55I',
      expiryDate: '2033-03-20',
      stockByWarehouse: { 'WH-MAIN': 115, 'WH-BAYB': 45, 'WH-COLD': 0 },
      totalStock: 160,
      reservedStock: 20,
      onOrderStock: 0
    },
    {
      id: 'PRD-110',
      sku: 'PWR-SMPS-240W',
      name: '24V 10A DIN-Rail Industrial Power Supply',
      category: 'Power Management',
      description: 'Active PFC, 94% peak efficiency with peak load capability up to 150%.',
      unitCost: 52.00,
      sellingPrice: 118.00,
      unit: 'pcs',
      minStock: 40,
      reorderQty: 80,
      preferredSupplierId: 'SUP-03',
      binLocation: 'C-02-11',
      lotNumber: 'LOT-2026-72J',
      expiryDate: '2030-07-15',
      stockByWarehouse: { 'WH-MAIN': 65, 'WH-BAYB': 25, 'WH-COLD': 0 },
      totalStock: 90,
      reservedStock: 15,
      onOrderStock: 0
    }
  ],

  suppliers: [
    {
      id: 'SUP-01',
      code: 'APEX-SEMI',
      name: 'Apex Semiconductor Corp',
      category: 'Computing & Gateways',
      contactPerson: 'David Chen',
      email: 'dchen@apexsemi.example.com',
      phone: '+1 (408) 555-0192',
      address: '4200 Technology Parkway, San Jose, CA',
      paymentTerms: 'Net 30',
      rating: 4.8,
      onTimeDeliveryPct: 97.4,
      avgLeadTimeDays: 7,
      currency: 'USD',
      activeOrdersCount: 2,
      suppliedProductIds: ['PRD-101', 'PRD-105']
    },
    {
      id: 'SUP-02',
      code: 'NIPPON-OPTO',
      name: 'Nippon Precision Optical Ltd',
      category: 'Sensors & Optics',
      contactPerson: 'Kenji Takahashi',
      email: 'takahashi.k@nippon-opto.example.com',
      phone: '+81 3 5555 8821',
      address: 'Chiyoda-ku, Marunouchi 2-Chome, Tokyo, Japan',
      paymentTerms: 'Net 45',
      rating: 4.9,
      onTimeDeliveryPct: 99.1,
      avgLeadTimeDays: 12,
      currency: 'USD',
      activeOrdersCount: 1,
      suppliedProductIds: ['PRD-102', 'PRD-107']
    },
    {
      id: 'SUP-03',
      code: 'VANGUARD-PWR',
      name: 'Vanguard Industrial Dynamics',
      category: 'Power & Mechanical',
      contactPerson: 'Sarah Jenkins',
      email: 'sjenkins@vanguarddyn.example.com',
      phone: '+1 (312) 555-4089',
      address: '880 Industrial Loop, Chicago, IL',
      paymentTerms: 'Net 30',
      rating: 4.6,
      onTimeDeliveryPct: 94.2,
      avgLeadTimeDays: 5,
      currency: 'USD',
      activeOrdersCount: 1,
      suppliedProductIds: ['PRD-103', 'PRD-108', 'PRD-110']
    },
    {
      id: 'SUP-04',
      code: 'NORDIC-OPTIC',
      name: 'Nordic Photonics Oy',
      category: 'Networking & Optics',
      contactPerson: 'Lars Lindqvist',
      email: 'llindqvist@nordicphotonics.example.com',
      phone: '+358 9 555 3110',
      address: 'Keilaranta 1, Espoo, Finland',
      paymentTerms: 'Net 60',
      rating: 4.7,
      onTimeDeliveryPct: 96.0,
      avgLeadTimeDays: 9,
      currency: 'USD',
      activeOrdersCount: 0,
      suppliedProductIds: ['PRD-104', 'PRD-109']
    },
    {
      id: 'SUP-05',
      code: 'MICRONIX-MEM',
      name: 'Micronix Solid State Solutions',
      category: 'Memory & Storage',
      contactPerson: 'Rachel Adams',
      email: 'radams@micronix-tech.example.com',
      phone: '+1 (512) 555-7720',
      address: '1200 Silicon Hills Blvd, Austin, TX',
      paymentTerms: 'Net 30',
      rating: 4.9,
      onTimeDeliveryPct: 98.8,
      avgLeadTimeDays: 4,
      currency: 'USD',
      activeOrdersCount: 1,
      suppliedProductIds: ['PRD-106']
    }
  ],

  customers: [
    {
      id: 'CUST-01',
      code: 'HYPERSCALE',
      name: 'HyperScale Systems International',
      contactPerson: 'Jonathan Miller',
      email: 'jmiller@hyperscale-sys.example.com',
      phone: '+1 (206) 555-0144',
      billingAddress: '500 Enterprise Way, Suite 1200, Seattle, WA',
      shippingAddress: 'Central DC Dock 4, Tukwila, WA',
      creditLimit: 250000.00,
      outstandingBalance: 68400.00,
      paymentTerms: 'Net 45',
      status: 'Good Standing',
      tier: 'Tier 1 Enterprise',
      totalOrdersCount: 18,
      lifetimeRevenue: 840200.00
    },
    {
      id: 'CUST-02',
      code: 'ORION-AUTO',
      name: 'Orion Autonomous Robotics Inc',
      contactPerson: 'Dr. Sophia Ramos',
      email: 's.ramos@orion-auto.example.com',
      phone: '+1 (617) 555-9201',
      billingAddress: '75 Innovation Center Drive, Cambridge, MA',
      shippingAddress: 'Robotics Proving Grounds, Bedford, MA',
      creditLimit: 120000.00,
      outstandingBalance: 42800.00,
      paymentTerms: 'Net 30',
      status: 'Good Standing',
      tier: 'Strategic Partner',
      totalOrdersCount: 11,
      lifetimeRevenue: 495100.00
    },
    {
      id: 'CUST-03',
      code: 'NEXUS-GRID',
      name: 'Nexus Smart Grid Energy Corp',
      contactPerson: 'Gregory Vance',
      email: 'gvance@nexusgrid.example.com',
      phone: '+1 (303) 555-7190',
      billingAddress: '1800 17th Street, Denver, CO',
      shippingAddress: 'Substation Assembly Yard B, Aurora, CO',
      creditLimit: 80000.00,
      outstandingBalance: 78500.00, // Near Credit Limit
      paymentTerms: 'Net 30',
      status: 'Credit Warning',
      tier: 'Tier 2 Commercial',
      totalOrdersCount: 7,
      lifetimeRevenue: 280000.00
    },
    {
      id: 'CUST-04',
      code: 'AEGIS-DEF',
      name: 'Aegis Aerospace & Defense Systems',
      contactPerson: 'Col. Mark Sterling (Ret.)',
      email: 'sterling.m@aegis-systems.example.com',
      phone: '+1 (703) 555-8830',
      billingAddress: '2400 Defense Boulevard, Arlington, VA',
      shippingAddress: 'Secure Facility Bay 7, Dulles, VA',
      creditLimit: 500000.00,
      outstandingBalance: 115000.00,
      paymentTerms: 'Net 60',
      status: 'Good Standing',
      tier: 'Tier 1 Enterprise',
      totalOrdersCount: 22,
      lifetimeRevenue: 1650000.00
    },
    {
      id: 'CUST-05',
      code: 'CYBERDYNE',
      name: 'Vortex Automation Solutions',
      contactPerson: 'Amanda Cole',
      email: 'acole@vortexauto.example.com',
      phone: '+1 (415) 555-6677',
      billingAddress: '350 Mission St, San Francisco, CA',
      shippingAddress: 'Assembly Lab, Fremont, CA',
      creditLimit: 50000.00,
      outstandingBalance: 14200.00,
      paymentTerms: 'Net 30',
      status: 'Good Standing',
      tier: 'Standard',
      totalOrdersCount: 5,
      lifetimeRevenue: 112000.00
    }
  ],

  purchaseOrders: [
    {
      id: 'PO-2026-001',
      supplierId: 'SUP-01',
      supplierName: 'Apex Semiconductor Corp',
      targetWarehouseId: 'WH-MAIN',
      orderDate: '2026-09-02',
      expectedDate: '2026-09-09',
      status: 'Fully Received', // Closed
      requiresApproval: true,
      approvalStatus: 'Approved',
      approvedBy: 'CFO (Executive)',
      approvedAt: '2026-09-03',
      paymentTerms: 'Net 30',
      items: [
        { productId: 'PRD-101', sku: 'CPU-ARM-OCTA', name: 'UltraCore ARM Octa-Core Processor Module', qty: 50, unitCost: 185.00, lineTotal: 9250.00, qtyReceived: 50 },
        { productId: 'PRD-105', sku: 'IOT-GW-5G', name: 'Ruggedized IP67 Industrial 5G Gateway', qty: 25, unitCost: 290.00, lineTotal: 7250.00, qtyReceived: 25 }
      ],
      subtotal: 16500.00,
      tax: 1320.00,
      shipping: 250.00,
      totalAmount: 18070.00,
      threeWayMatched: true,
      notes: 'Completed delivery for Q3 baseline compute restocking.'
    },
    {
      id: 'PO-2026-002',
      supplierId: 'SUP-02',
      supplierName: 'Nippon Precision Optical Ltd',
      targetWarehouseId: 'WH-MAIN',
      orderDate: '2026-09-10',
      expectedDate: '2026-09-18',
      status: 'Approved', // Ready for Receiving GRN
      requiresApproval: true,
      approvalStatus: 'Approved',
      approvedBy: 'Procurement Director',
      approvedAt: '2026-09-11',
      paymentTerms: 'Net 45',
      items: [
        { productId: 'PRD-102', sku: 'SNS-LIDAR-360', name: 'Solid-State 360° LiDAR Sensor Suite', qty: 30, unitCost: 420.00, lineTotal: 12600.00, qtyReceived: 0 }
      ],
      subtotal: 12600.00,
      tax: 1008.00,
      shipping: 180.00,
      totalAmount: 13788.00,
      threeWayMatched: false,
      notes: 'Air freight expedited via Tokyo Narita to DFW.'
    },
    {
      id: 'PO-2026-003',
      supplierId: 'SUP-03',
      supplierName: 'Vanguard Industrial Dynamics',
      targetWarehouseId: 'WH-MAIN',
      orderDate: '2026-09-15',
      expectedDate: '2026-09-22',
      status: 'Pending Approval', // Needs CFO / Director approval (> $5,000)
      requiresApproval: true,
      approvalStatus: 'Pending',
      approvedBy: null,
      approvedAt: null,
      paymentTerms: 'Net 30',
      items: [
        { productId: 'PRD-103', sku: 'PWR-BMS-48V', name: 'Modular Smart 48V Battery Management System', qty: 120, unitCost: 74.50, lineTotal: 8940.00, qtyReceived: 0 },
        { productId: 'PRD-108', sku: 'ENC-ALUM-DIN', name: 'Extruded Aluminum Enclosure (DIN Mount)', qty: 200, unitCost: 22.00, lineTotal: 4400.00, qtyReceived: 0 },
        { productId: 'PRD-110', sku: 'PWR-SMPS-240W', name: '24V 10A DIN-Rail Industrial Power Supply', qty: 80, unitCost: 52.00, lineTotal: 4160.00, qtyReceived: 0 }
      ],
      subtotal: 17500.00,
      tax: 1400.00,
      shipping: 350.00,
      totalAmount: 19250.00,
      threeWayMatched: false,
      notes: 'Quarterly power infrastructure restocking package.'
    },
    {
      id: 'PO-2026-004',
      supplierId: 'SUP-05',
      supplierName: 'Micronix Solid State Solutions',
      targetWarehouseId: 'WH-BAYB',
      orderDate: '2026-09-16',
      expectedDate: '2026-09-21',
      status: 'Approved',
      requiresApproval: false,
      approvalStatus: 'Approved',
      approvedBy: 'Procurement Manager',
      approvedAt: '2026-09-16',
      paymentTerms: 'Net 30',
      items: [
        { productId: 'PRD-106', sku: 'MEM-DDR5-ECC', name: '64GB Industrial ECC DDR5 SO-DIMM', qty: 40, unitCost: 95.00, lineTotal: 3800.00, qtyReceived: 0 }
      ],
      subtotal: 3800.00,
      tax: 304.00,
      shipping: 75.00,
      totalAmount: 4179.00,
      threeWayMatched: false,
      notes: 'Standard replenishment under $5k threshold.'
    }
  ],

  salesOrders: [
    {
      id: 'SO-2026-101',
      customerId: 'CUST-01',
      customerName: 'HyperScale Systems International',
      sourceWarehouseId: 'WH-MAIN',
      orderDate: '2026-09-05',
      status: 'Dispatched & Invoiced',
      paymentTerms: 'Net 45',
      requiresApproval: false,
      approvalStatus: 'Approved',
      items: [
        { productId: 'PRD-101', sku: 'CPU-ARM-OCTA', name: 'UltraCore ARM Octa-Core Processor Module', qty: 25, unitPrice: 340.00, lineTotal: 8500.00 },
        { productId: 'PRD-104', sku: 'OPT-100G-QSFP', name: '100G QSFP28 Single-Mode Optical Transceiver', qty: 50, unitPrice: 245.00, lineTotal: 12250.00 },
        { productId: 'PRD-106', sku: 'MEM-DDR5-ECC', name: '64GB Industrial ECC DDR5 SO-DIMM', qty: 30, unitPrice: 195.00, lineTotal: 5850.00 }
      ],
      subtotal: 26600.00,
      discountPct: 5,
      discountAmount: 1330.00,
      tax: 2021.60,
      shipping: 220.00,
      totalAmount: 27511.60,
      trackingNumber: 'TRK-FEDEX-9982410',
      invoiceNumber: 'INV-2026-081',
      invoiceStatus: 'Issued'
    },
    {
      id: 'SO-2026-102',
      customerId: 'CUST-02',
      customerName: 'Orion Autonomous Robotics Inc',
      sourceWarehouseId: 'WH-MAIN',
      orderDate: '2026-09-14',
      status: 'Confirmed - Stock Reserved', // Ready to Dispatch!
      paymentTerms: 'Net 30',
      requiresApproval: false,
      approvalStatus: 'Approved',
      items: [
        { productId: 'PRD-102', sku: 'SNS-LIDAR-360', name: 'Solid-State 360° LiDAR Sensor Suite', qty: 10, unitPrice: 780.00, lineTotal: 7800.00 },
        { productId: 'PRD-107', sku: 'SNS-IMU-6DOF', name: 'Precision MEMS 6-DoF Inertial Unit', qty: 50, unitPrice: 85.00, lineTotal: 4250.00 }
      ],
      subtotal: 12050.00,
      discountPct: 0,
      discountAmount: 0.00,
      tax: 964.00,
      shipping: 150.00,
      totalAmount: 13164.00,
      trackingNumber: null,
      invoiceNumber: null,
      invoiceStatus: 'Pending Dispatch'
    },
    {
      id: 'SO-2026-103',
      customerId: 'CUST-04',
      customerName: 'Aegis Aerospace & Defense Systems',
      sourceWarehouseId: 'WH-MAIN',
      orderDate: '2026-09-16',
      status: 'Pending Approval', // Needs Sales Director approval (Discount: 18% > 15%)
      paymentTerms: 'Net 60',
      requiresApproval: true,
      approvalType: 'Sales Discount > 15%',
      approvalStatus: 'Pending',
      items: [
        { productId: 'PRD-105', sku: 'IOT-GW-5G', name: 'Ruggedized IP67 Industrial 5G Gateway', qty: 12, unitPrice: 560.00, lineTotal: 6720.00 },
        { productId: 'PRD-103', sku: 'PWR-BMS-48V', name: 'Modular Smart 48V Battery Management System', qty: 40, unitPrice: 155.00, lineTotal: 6200.00 }
      ],
      subtotal: 12920.00,
      discountPct: 18, // Triggers approval rule!
      discountAmount: 2325.60,
      tax: 847.55,
      shipping: 200.00,
      totalAmount: 11641.95,
      trackingNumber: null,
      invoiceNumber: null,
      invoiceStatus: 'Blocked by Approval'
    },
    {
      id: 'SO-2026-104',
      customerId: 'CUST-05',
      customerName: 'Vortex Automation Solutions',
      sourceWarehouseId: 'WH-BAYB',
      orderDate: '2026-09-16',
      status: 'Draft Quotation',
      paymentTerms: 'Net 30',
      requiresApproval: false,
      approvalStatus: 'Draft',
      items: [
        { productId: 'PRD-109', sku: 'CAB-M12-8PIN', name: 'Shielded M12 8-Pin Industrial Ethernet Cable (5m)', qty: 20, unitPrice: 32.50, lineTotal: 650.00 },
        { productId: 'PRD-110', sku: 'PWR-SMPS-240W', name: '24V 10A DIN-Rail Industrial Power Supply', qty: 15, unitPrice: 118.00, lineTotal: 1770.00 }
      ],
      subtotal: 2420.00,
      discountPct: 0,
      discountAmount: 0.00,
      tax: 193.60,
      shipping: 60.00,
      totalAmount: 2673.60,
      trackingNumber: null,
      invoiceNumber: null,
      invoiceStatus: 'Quotation'
    }
  ],

  approvals: [
    {
      id: 'APR-2026-01',
      category: 'Procurement',
      targetId: 'PO-2026-003',
      targetRef: 'PO-2026-003 (Vanguard Industrial Dynamics)',
      amount: 19250.00,
      requester: 'Marcus Vance (Procurement Lead)',
      requiredRole: 'CFO / Finance Director',
      reason: 'Standard Rule: All Purchase Orders exceeding $5,000.00 require executive sign-off before vendor transmission.',
      status: 'Pending',
      submittedAt: '2026-09-15 14:32',
      decidedAt: null,
      decidedBy: null,
      comments: ''
    },
    {
      id: 'APR-2026-02',
      category: 'Sales Discount',
      targetId: 'SO-2026-103',
      targetRef: 'SO-2026-103 (Aegis Aerospace)',
      amount: 11641.95,
      requester: 'Amanda Rodriguez (Senior Account Exec)',
      requiredRole: 'Sales Director',
      reason: 'Standard Rule: High-volume customer negotiation discount of 18.0% requested (Corporate threshold is 15.0%).',
      status: 'Pending',
      submittedAt: '2026-09-16 10:15',
      decidedAt: null,
      decidedBy: null,
      comments: ''
    },
    {
      id: 'APR-2026-03',
      category: 'Inventory Write-Off',
      targetId: 'ADJ-2026-09',
      targetRef: 'Damaged Transit Batch (Optical Modules)',
      amount: 1210.00,
      requester: 'Derrick Hall (Warehouse Supervisor)',
      requiredRole: 'Operations Lead',
      reason: 'Physical inspection detected moisture breach in shipping pallet for 11x 100G Optical Modules.',
      status: 'Pending',
      submittedAt: '2026-09-16 11:45',
      decidedAt: null,
      decidedBy: null,
      comments: ''
    }
  ],

  stockMovements: [
    {
      id: 'MOV-2026-001',
      timestamp: '2026-09-09 11:20',
      type: 'Goods Receipt (PO)',
      referenceId: 'PO-2026-001',
      productId: 'PRD-101',
      sku: 'CPU-ARM-OCTA',
      productName: 'UltraCore ARM Octa-Core Processor Module',
      warehouseId: 'WH-MAIN',
      qtyChange: +50,
      balanceAfter: 140,
      operator: 'Marcus Vance',
      notes: 'Dock 2 inbound verified with packing slip.'
    },
    {
      id: 'MOV-2026-002',
      timestamp: '2026-09-09 11:25',
      type: 'Goods Receipt (PO)',
      referenceId: 'PO-2026-001',
      productId: 'PRD-105',
      sku: 'IOT-GW-5G',
      productName: 'Ruggedized IP67 Industrial 5G Gateway',
      warehouseId: 'WH-MAIN',
      qtyChange: +25,
      balanceAfter: 75,
      operator: 'Marcus Vance',
      notes: 'Received into Bin B-11-04.'
    },
    {
      id: 'MOV-2026-003',
      timestamp: '2026-09-08 16:40',
      type: 'Sales Fulfillment',
      referenceId: 'SO-2026-101',
      productId: 'PRD-104',
      sku: 'OPT-100G-QSFP',
      productName: '100G QSFP28 Optical Transceiver',
      warehouseId: 'WH-MAIN',
      qtyChange: -50,
      balanceAfter: 28,
      operator: 'Elena Rostova',
      notes: 'Picked & packed for FedEx overnight dispatch.'
    },
    {
      id: 'MOV-2026-004',
      timestamp: '2026-09-12 09:15',
      type: 'Inter-Warehouse Transfer',
      referenceId: 'XFER-084',
      productId: 'PRD-106',
      sku: 'MEM-DDR5-ECC',
      productName: '64GB Industrial ECC DDR5 SO-DIMM',
      warehouseId: 'WH-MAIN -> WH-BAYB',
      qtyChange: 20,
      balanceAfter: 230,
      operator: 'Derrick Hall',
      notes: 'Internal transfer to balance Austin tech lab stock.'
    }
  ]
};
